version: '3.9'

services:

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ong
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db

  wordpress:
    image: wordpress
    container_name: wordpress_app
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: postgres
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: ong
    depends_on:
      - db